# Generated by Django 2.2.16 on 2022-09-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220903_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriterecipe',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
