# Generated by Django 2.2.16 on 2022-09-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_ingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
