# Generated by Django 2.2.16 on 2022-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220906_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
