# Generated by Django 2.2.16 on 2022-09-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20220908_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriterecipe',
            name='amount',
        ),
    ]
