# Generated by Django 2.2.16 on 2022-09-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20220913_1008'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_author_name',
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='unique_author_recipe'),
        ),
    ]
